### PR TITLE
Create acs-ai-index.md

### PR DESCRIPTION
**Pull request by vac0224**
added file acs-ai-index.md

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by daysha-carter** [comment]
@sign-off

**Comment by daysha-carter** [comment]
#sign-off

**Comment by vac0224** [comment]
@akania can you please approve and merge so we can generate an AKA link. I am still editing the files on my machine. Thanks!

**Comment by daysha-carter** [comment]
#sign-off

**Comment by daysha-carter** [comment]
#sign-off

**Review by akania — APPROVED** [review]

**Pull request merged**
